/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PsychologistRouteImport } from './routes/psychologist'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreensIndexRouteImport } from './routes/screens.index'
import { Route as PsychologistIndexRouteImport } from './routes/psychologist.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ScreensIdRouteImport } from './routes/screens.$id'
import { Route as PsychologistSettingsRouteImport } from './routes/psychologist.settings'
import { Route as PsychologistProfileRouteImport } from './routes/psychologist.profile'
import { Route as PsychologistPendingRouteImport } from './routes/psychologist.pending'
import { Route as PsychologistPatientsRouteImport } from './routes/psychologist.patients'
import { Route as PsychologistNotesRouteImport } from './routes/psychologist.notes'
import { Route as PsychologistMessagesRouteImport } from './routes/psychologist.messages'
import { Route as PsychologistAvailabilityRouteImport } from './routes/psychologist.availability'
import { Route as PsychologistAppointmentsRouteImport } from './routes/psychologist.appointments'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientRecordsRouteImport } from './routes/patient.records'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientMessagesRouteImport } from './routes/patient.messages'
import { Route as PatientFindRouteImport } from './routes/patient.find'
import { Route as PatientAssessmentRouteImport } from './routes/patient.assessment'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingReviewRouteImport } from './routes/onboarding.review'
import { Route as OnboardingPendingRouteImport } from './routes/onboarding.pending'
import { Route as OnboardingDocumentsRouteImport } from './routes/onboarding.documents'
import { Route as OnboardingCredentialsRouteImport } from './routes/onboarding.credentials'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthAccountCreatedRouteImport } from './routes/auth.account-created'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminVerificationIndexRouteImport } from './routes/admin.verification.index'
import { Route as PsychologistPatientsIdRouteImport } from './routes/psychologist.patients.$id'
import { Route as PatientSessionIdRouteImport } from './routes/patient.session.$id'
import { Route as PatientPsychologistIdRouteImport } from './routes/patient.psychologist.$id'
import { Route as PatientBookIdRouteImport } from './routes/patient.book.$id'
import { Route as AdminVerificationIdRouteImport } from './routes/admin.verification.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologistRoute = PsychologistRouteImport.update({
  id: '/psychologist',
  path: '/psychologist',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensIndexRoute = ScreensIndexRouteImport.update({
  id: '/screens/',
  path: '/screens/',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologistIndexRoute = PsychologistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PsychologistRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ScreensIdRoute = ScreensIdRouteImport.update({
  id: '/screens/$id',
  path: '/screens/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologistSettingsRoute = PsychologistSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PsychologistRoute,
} as any)
const PsychologistProfileRoute = PsychologistProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PsychologistRoute,
} as any)
const PsychologistPendingRoute = PsychologistPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => PsychologistRoute,
} as any)
const PsychologistPatientsRoute = PsychologistPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => PsychologistRoute,
} as any)
const PsychologistNotesRoute = PsychologistNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => PsychologistRoute,
} as any)
const PsychologistMessagesRoute = PsychologistMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PsychologistRoute,
} as any)
const PsychologistAvailabilityRoute =
  PsychologistAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => PsychologistRoute,
  } as any)
const PsychologistAppointmentsRoute =
  PsychologistAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => PsychologistRoute,
  } as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientRecordsRoute = PatientRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMessagesRoute = PatientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientRoute,
} as any)
const PatientFindRoute = PatientFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAssessmentRoute = PatientAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingReviewRoute = OnboardingReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPendingRoute = OnboardingPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDocumentsRoute = OnboardingDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCredentialsRoute = OnboardingCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountCreatedRoute = AuthAccountCreatedRouteImport.update({
  id: '/account-created',
  path: '/account-created',
  getParentRoute: () => AuthRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationIndexRoute = AdminVerificationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminVerificationRoute,
} as any)
const PsychologistPatientsIdRoute = PsychologistPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PsychologistPatientsRoute,
} as any)
const PatientSessionIdRoute = PatientSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPsychologistIdRoute = PatientPsychologistIdRouteImport.update({
  id: '/psychologist/$id',
  path: '/psychologist/$id',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBookIdRoute = PatientBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => PatientRoute,
} as any)
const AdminVerificationIdRoute = AdminVerificationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVerificationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/psychologist': typeof PsychologistRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRouteWithChildren
  '/auth/account-created': typeof AuthAccountCreatedRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/onboarding/credentials': typeof OnboardingCredentialsRoute
  '/onboarding/documents': typeof OnboardingDocumentsRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assessment': typeof PatientAssessmentRoute
  '/patient/find': typeof PatientFindRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/psychologist/appointments': typeof PsychologistAppointmentsRoute
  '/psychologist/availability': typeof PsychologistAvailabilityRoute
  '/psychologist/messages': typeof PsychologistMessagesRoute
  '/psychologist/notes': typeof PsychologistNotesRoute
  '/psychologist/patients': typeof PsychologistPatientsRouteWithChildren
  '/psychologist/pending': typeof PsychologistPendingRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/psychologist/settings': typeof PsychologistSettingsRoute
  '/screens/$id': typeof ScreensIdRoute
  '/admin/': typeof AdminIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/psychologist/': typeof PsychologistIndexRoute
  '/screens/': typeof ScreensIndexRoute
  '/admin/verification/$id': typeof AdminVerificationIdRoute
  '/patient/book/$id': typeof PatientBookIdRoute
  '/patient/psychologist/$id': typeof PatientPsychologistIdRoute
  '/patient/session/$id': typeof PatientSessionIdRoute
  '/psychologist/patients/$id': typeof PsychologistPatientsIdRoute
  '/admin/verification/': typeof AdminVerificationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/account-created': typeof AuthAccountCreatedRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/onboarding/credentials': typeof OnboardingCredentialsRoute
  '/onboarding/documents': typeof OnboardingDocumentsRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assessment': typeof PatientAssessmentRoute
  '/patient/find': typeof PatientFindRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/psychologist/appointments': typeof PsychologistAppointmentsRoute
  '/psychologist/availability': typeof PsychologistAvailabilityRoute
  '/psychologist/messages': typeof PsychologistMessagesRoute
  '/psychologist/notes': typeof PsychologistNotesRoute
  '/psychologist/patients': typeof PsychologistPatientsRouteWithChildren
  '/psychologist/pending': typeof PsychologistPendingRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/psychologist/settings': typeof PsychologistSettingsRoute
  '/screens/$id': typeof ScreensIdRoute
  '/admin': typeof AdminIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/patient': typeof PatientIndexRoute
  '/psychologist': typeof PsychologistIndexRoute
  '/screens': typeof ScreensIndexRoute
  '/admin/verification/$id': typeof AdminVerificationIdRoute
  '/patient/book/$id': typeof PatientBookIdRoute
  '/patient/psychologist/$id': typeof PatientPsychologistIdRoute
  '/patient/session/$id': typeof PatientSessionIdRoute
  '/psychologist/patients/$id': typeof PsychologistPatientsIdRoute
  '/admin/verification': typeof AdminVerificationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/psychologist': typeof PsychologistRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRouteWithChildren
  '/auth/account-created': typeof AuthAccountCreatedRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/onboarding/credentials': typeof OnboardingCredentialsRoute
  '/onboarding/documents': typeof OnboardingDocumentsRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assessment': typeof PatientAssessmentRoute
  '/patient/find': typeof PatientFindRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/psychologist/appointments': typeof PsychologistAppointmentsRoute
  '/psychologist/availability': typeof PsychologistAvailabilityRoute
  '/psychologist/messages': typeof PsychologistMessagesRoute
  '/psychologist/notes': typeof PsychologistNotesRoute
  '/psychologist/patients': typeof PsychologistPatientsRouteWithChildren
  '/psychologist/pending': typeof PsychologistPendingRoute
  '/psychologist/profile': typeof PsychologistProfileRoute
  '/psychologist/settings': typeof PsychologistSettingsRoute
  '/screens/$id': typeof ScreensIdRoute
  '/admin/': typeof AdminIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/psychologist/': typeof PsychologistIndexRoute
  '/screens/': typeof ScreensIndexRoute
  '/admin/verification/$id': typeof AdminVerificationIdRoute
  '/patient/book/$id': typeof PatientBookIdRoute
  '/patient/psychologist/$id': typeof PatientPsychologistIdRoute
  '/patient/session/$id': typeof PatientSessionIdRoute
  '/psychologist/patients/$id': typeof PsychologistPatientsIdRoute
  '/admin/verification/': typeof AdminVerificationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/mission'
    | '/onboarding'
    | '/patient'
    | '/privacy'
    | '/psychologist'
    | '/terms'
    | '/admin/appointments'
    | '/admin/content'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/auth/account-created'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/onboarding/credentials'
    | '/onboarding/documents'
    | '/onboarding/pending'
    | '/onboarding/review'
    | '/onboarding/welcome'
    | '/patient/appointments'
    | '/patient/assessment'
    | '/patient/find'
    | '/patient/messages'
    | '/patient/profile'
    | '/patient/records'
    | '/patient/settings'
    | '/psychologist/appointments'
    | '/psychologist/availability'
    | '/psychologist/messages'
    | '/psychologist/notes'
    | '/psychologist/patients'
    | '/psychologist/pending'
    | '/psychologist/profile'
    | '/psychologist/settings'
    | '/screens/$id'
    | '/admin/'
    | '/onboarding/'
    | '/patient/'
    | '/psychologist/'
    | '/screens/'
    | '/admin/verification/$id'
    | '/patient/book/$id'
    | '/patient/psychologist/$id'
    | '/patient/session/$id'
    | '/psychologist/patients/$id'
    | '/admin/verification/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/mission'
    | '/privacy'
    | '/terms'
    | '/admin/appointments'
    | '/admin/content'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/account-created'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/onboarding/credentials'
    | '/onboarding/documents'
    | '/onboarding/pending'
    | '/onboarding/review'
    | '/onboarding/welcome'
    | '/patient/appointments'
    | '/patient/assessment'
    | '/patient/find'
    | '/patient/messages'
    | '/patient/profile'
    | '/patient/records'
    | '/patient/settings'
    | '/psychologist/appointments'
    | '/psychologist/availability'
    | '/psychologist/messages'
    | '/psychologist/notes'
    | '/psychologist/patients'
    | '/psychologist/pending'
    | '/psychologist/profile'
    | '/psychologist/settings'
    | '/screens/$id'
    | '/admin'
    | '/onboarding'
    | '/patient'
    | '/psychologist'
    | '/screens'
    | '/admin/verification/$id'
    | '/patient/book/$id'
    | '/patient/psychologist/$id'
    | '/patient/session/$id'
    | '/psychologist/patients/$id'
    | '/admin/verification'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/mission'
    | '/onboarding'
    | '/patient'
    | '/privacy'
    | '/psychologist'
    | '/terms'
    | '/admin/appointments'
    | '/admin/content'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/auth/account-created'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/onboarding/credentials'
    | '/onboarding/documents'
    | '/onboarding/pending'
    | '/onboarding/review'
    | '/onboarding/welcome'
    | '/patient/appointments'
    | '/patient/assessment'
    | '/patient/find'
    | '/patient/messages'
    | '/patient/profile'
    | '/patient/records'
    | '/patient/settings'
    | '/psychologist/appointments'
    | '/psychologist/availability'
    | '/psychologist/messages'
    | '/psychologist/notes'
    | '/psychologist/patients'
    | '/psychologist/pending'
    | '/psychologist/profile'
    | '/psychologist/settings'
    | '/screens/$id'
    | '/admin/'
    | '/onboarding/'
    | '/patient/'
    | '/psychologist/'
    | '/screens/'
    | '/admin/verification/$id'
    | '/patient/book/$id'
    | '/patient/psychologist/$id'
    | '/patient/session/$id'
    | '/psychologist/patients/$id'
    | '/admin/verification/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MissionRoute: typeof MissionRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  PsychologistRoute: typeof PsychologistRouteWithChildren
  TermsRoute: typeof TermsRoute
  ScreensIdRoute: typeof ScreensIdRoute
  ScreensIndexRoute: typeof ScreensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychologist': {
      id: '/psychologist'
      path: '/psychologist'
      fullPath: '/psychologist'
      preLoaderRoute: typeof PsychologistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens/': {
      id: '/screens/'
      path: '/screens'
      fullPath: '/screens/'
      preLoaderRoute: typeof ScreensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychologist/': {
      id: '/psychologist/'
      path: '/'
      fullPath: '/psychologist/'
      preLoaderRoute: typeof PsychologistIndexRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/screens/$id': {
      id: '/screens/$id'
      path: '/screens/$id'
      fullPath: '/screens/$id'
      preLoaderRoute: typeof ScreensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychologist/settings': {
      id: '/psychologist/settings'
      path: '/settings'
      fullPath: '/psychologist/settings'
      preLoaderRoute: typeof PsychologistSettingsRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/psychologist/profile': {
      id: '/psychologist/profile'
      path: '/profile'
      fullPath: '/psychologist/profile'
      preLoaderRoute: typeof PsychologistProfileRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/psychologist/pending': {
      id: '/psychologist/pending'
      path: '/pending'
      fullPath: '/psychologist/pending'
      preLoaderRoute: typeof PsychologistPendingRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/psychologist/patients': {
      id: '/psychologist/patients'
      path: '/patients'
      fullPath: '/psychologist/patients'
      preLoaderRoute: typeof PsychologistPatientsRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/psychologist/notes': {
      id: '/psychologist/notes'
      path: '/notes'
      fullPath: '/psychologist/notes'
      preLoaderRoute: typeof PsychologistNotesRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/psychologist/messages': {
      id: '/psychologist/messages'
      path: '/messages'
      fullPath: '/psychologist/messages'
      preLoaderRoute: typeof PsychologistMessagesRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/psychologist/availability': {
      id: '/psychologist/availability'
      path: '/availability'
      fullPath: '/psychologist/availability'
      preLoaderRoute: typeof PsychologistAvailabilityRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/psychologist/appointments': {
      id: '/psychologist/appointments'
      path: '/appointments'
      fullPath: '/psychologist/appointments'
      preLoaderRoute: typeof PsychologistAppointmentsRouteImport
      parentRoute: typeof PsychologistRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/records': {
      id: '/patient/records'
      path: '/records'
      fullPath: '/patient/records'
      preLoaderRoute: typeof PatientRecordsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/messages': {
      id: '/patient/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientMessagesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/find': {
      id: '/patient/find'
      path: '/find'
      fullPath: '/patient/find'
      preLoaderRoute: typeof PatientFindRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/assessment': {
      id: '/patient/assessment'
      path: '/assessment'
      fullPath: '/patient/assessment'
      preLoaderRoute: typeof PatientAssessmentRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/review': {
      id: '/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof OnboardingReviewRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/pending': {
      id: '/onboarding/pending'
      path: '/pending'
      fullPath: '/onboarding/pending'
      preLoaderRoute: typeof OnboardingPendingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/documents': {
      id: '/onboarding/documents'
      path: '/documents'
      fullPath: '/onboarding/documents'
      preLoaderRoute: typeof OnboardingDocumentsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/credentials': {
      id: '/onboarding/credentials'
      path: '/credentials'
      fullPath: '/onboarding/credentials'
      preLoaderRoute: typeof OnboardingCredentialsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/account-created': {
      id: '/auth/account-created'
      path: '/account-created'
      fullPath: '/auth/account-created'
      preLoaderRoute: typeof AuthAccountCreatedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification/': {
      id: '/admin/verification/'
      path: '/'
      fullPath: '/admin/verification/'
      preLoaderRoute: typeof AdminVerificationIndexRouteImport
      parentRoute: typeof AdminVerificationRoute
    }
    '/psychologist/patients/$id': {
      id: '/psychologist/patients/$id'
      path: '/$id'
      fullPath: '/psychologist/patients/$id'
      preLoaderRoute: typeof PsychologistPatientsIdRouteImport
      parentRoute: typeof PsychologistPatientsRoute
    }
    '/patient/session/$id': {
      id: '/patient/session/$id'
      path: '/session/$id'
      fullPath: '/patient/session/$id'
      preLoaderRoute: typeof PatientSessionIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/psychologist/$id': {
      id: '/patient/psychologist/$id'
      path: '/psychologist/$id'
      fullPath: '/patient/psychologist/$id'
      preLoaderRoute: typeof PatientPsychologistIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/book/$id': {
      id: '/patient/book/$id'
      path: '/book/$id'
      fullPath: '/patient/book/$id'
      preLoaderRoute: typeof PatientBookIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/admin/verification/$id': {
      id: '/admin/verification/$id'
      path: '/$id'
      fullPath: '/admin/verification/$id'
      preLoaderRoute: typeof AdminVerificationIdRouteImport
      parentRoute: typeof AdminVerificationRoute
    }
  }
}

interface AdminVerificationRouteChildren {
  AdminVerificationIdRoute: typeof AdminVerificationIdRoute
  AdminVerificationIndexRoute: typeof AdminVerificationIndexRoute
}

const AdminVerificationRouteChildren: AdminVerificationRouteChildren = {
  AdminVerificationIdRoute: AdminVerificationIdRoute,
  AdminVerificationIndexRoute: AdminVerificationIndexRoute,
}

const AdminVerificationRouteWithChildren =
  AdminVerificationRoute._addFileChildren(AdminVerificationRouteChildren)

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthAccountCreatedRoute: typeof AuthAccountCreatedRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountCreatedRoute: AuthAccountCreatedRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCredentialsRoute: typeof OnboardingCredentialsRoute
  OnboardingDocumentsRoute: typeof OnboardingDocumentsRoute
  OnboardingPendingRoute: typeof OnboardingPendingRoute
  OnboardingReviewRoute: typeof OnboardingReviewRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCredentialsRoute: OnboardingCredentialsRoute,
  OnboardingDocumentsRoute: OnboardingDocumentsRoute,
  OnboardingPendingRoute: OnboardingPendingRoute,
  OnboardingReviewRoute: OnboardingReviewRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientAssessmentRoute: typeof PatientAssessmentRoute
  PatientFindRoute: typeof PatientFindRoute
  PatientMessagesRoute: typeof PatientMessagesRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientRecordsRoute: typeof PatientRecordsRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientBookIdRoute: typeof PatientBookIdRoute
  PatientPsychologistIdRoute: typeof PatientPsychologistIdRoute
  PatientSessionIdRoute: typeof PatientSessionIdRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientAssessmentRoute: PatientAssessmentRoute,
  PatientFindRoute: PatientFindRoute,
  PatientMessagesRoute: PatientMessagesRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientRecordsRoute: PatientRecordsRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientBookIdRoute: PatientBookIdRoute,
  PatientPsychologistIdRoute: PatientPsychologistIdRoute,
  PatientSessionIdRoute: PatientSessionIdRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PsychologistPatientsRouteChildren {
  PsychologistPatientsIdRoute: typeof PsychologistPatientsIdRoute
}

const PsychologistPatientsRouteChildren: PsychologistPatientsRouteChildren = {
  PsychologistPatientsIdRoute: PsychologistPatientsIdRoute,
}

const PsychologistPatientsRouteWithChildren =
  PsychologistPatientsRoute._addFileChildren(PsychologistPatientsRouteChildren)

interface PsychologistRouteChildren {
  PsychologistAppointmentsRoute: typeof PsychologistAppointmentsRoute
  PsychologistAvailabilityRoute: typeof PsychologistAvailabilityRoute
  PsychologistMessagesRoute: typeof PsychologistMessagesRoute
  PsychologistNotesRoute: typeof PsychologistNotesRoute
  PsychologistPatientsRoute: typeof PsychologistPatientsRouteWithChildren
  PsychologistPendingRoute: typeof PsychologistPendingRoute
  PsychologistProfileRoute: typeof PsychologistProfileRoute
  PsychologistSettingsRoute: typeof PsychologistSettingsRoute
  PsychologistIndexRoute: typeof PsychologistIndexRoute
}

const PsychologistRouteChildren: PsychologistRouteChildren = {
  PsychologistAppointmentsRoute: PsychologistAppointmentsRoute,
  PsychologistAvailabilityRoute: PsychologistAvailabilityRoute,
  PsychologistMessagesRoute: PsychologistMessagesRoute,
  PsychologistNotesRoute: PsychologistNotesRoute,
  PsychologistPatientsRoute: PsychologistPatientsRouteWithChildren,
  PsychologistPendingRoute: PsychologistPendingRoute,
  PsychologistProfileRoute: PsychologistProfileRoute,
  PsychologistSettingsRoute: PsychologistSettingsRoute,
  PsychologistIndexRoute: PsychologistIndexRoute,
}

const PsychologistRouteWithChildren = PsychologistRoute._addFileChildren(
  PsychologistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MissionRoute: MissionRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  PsychologistRoute: PsychologistRouteWithChildren,
  TermsRoute: TermsRoute,
  ScreensIdRoute: ScreensIdRoute,
  ScreensIndexRoute: ScreensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
